export const dummy = [
  {
    id: 1,
    title: 'qweqweqweaasdasdasdasdsdsadasdwq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user1',
    createAt: '20222342-01-02',
    answers: 2,
    votes: 3,
    views: 4,
  },
  {
    id: 2,
    title:
      '배ㅔㅈㄷㅊㅂ재ㅔ다ㅡㅐㅂㅈㅊ댑제ㅏㄷㅂ잧대ㅔㅂ자대ㅔㅡㅏㅂ제ㅐㅊ다ㅂㅈㄷㅊㅂㅈ대츱ㅈ더체배잳ㅂ잳ㅊ쟃뎆드ㅐㅂㅈ대찹재ㅔ',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user2',
    createAt: '2021241242-01-0100',
    answers: 2,
    votes: 3,
    views: 4,
  },
  {
    id: 4,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user3',
    createAt: '2021241242-01-02',
    answers: 1,
    votes: 2,
    views: 4,
  },
  {
    id: 4,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user4',
    createAt: '2022-01-02',
    answers: 3,
    votes: 5,
    views: 4,
  },
  {
    id: 5,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
  {
    id: 6,
    title: 'ㅂ제ㅏㅣㄷ겇즤ㅏ덛자ㅣ더ㅣㅏㅂㅈㅊ더ㅓㅣ',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 4,
    views: 4,
  },
  {
    id: 7,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 4,
    views: 4,
  },
  {
    id: 8,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 4,
    views: 4,
  },
  {
    id: 9,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 4,
    views: 4,
  },
  {
    id: 10,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 4,
    views: 4,
  },
  {
    id: 11,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
  {
    id: 12,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
  {
    id: 13,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
  {
    id: 14,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
  {
    id: 15,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
];
