export const dummy = [
  {
    id: 1,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user1',
    createAt: '20222342-01-02',
    answers: 2,
    votes: 3,
    views: 4,
  },
  {
    id: 2,
    title:
      'qweqweqwewqqweqweeqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwqwewewqweqweqwewqqweqweeqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwqwewewqweqweqwewqqweqweeqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwqwewew',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user2',
    createAt: '2021241242-01-0100',
    answers: 2,
    votes: 3,
    views: 4,
  },
  {
    id: 4,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user3',
    createAt: '2021241242-01-02',
    answers: 1,
    votes: 2,
    views: 4,
  },
  {
    id: 4,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user4',
    createAt: '2022-01-02',
    answers: 3,
    votes: 5,
    views: 4,
  },
  {
    id: 5,
    title: 'qweqweqwewq',
    contents: '콘텐츠콘텐츠콘텐츠',
    userName: 'user5',
    createAt: '2022-01-05',
    answers: 3,
    votes: 2,
    views: 4,
  },
];
