spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seb014?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yourPassword


  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true
  jwt:
    secret: adsa
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
